apiVersion : apps/v1
kind: Deployment
metadata:
  name: "tinc-mesh-tunnel"
  namespace : "product"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "tinc-mesh-tunnel"
  template:
    metadata:
      labels:
        app: "tinc-mesh-tunnel"
    spec:
      volumes:
        - name: css-tinc-properties
          secret:
            secretName: css-tinc-properties
        - name: test-volume
          hostPath:
            # directory location on host
            path: /etc/tinc/
            # this field is optional
            type: Directory
        - name: test-volume1
          hostPath:
            # directory location on host
            path: /dev/net/
            # this field is optional
            type: Directory
        - name: test-volume2
          hostPath:
             path: /proc/sys/net/ipv4/conf/
             type: Directory
        #- name: test-volume3
          #hostPath:
             #path: /proc/sys/net/ipv4/conf/tun0/
             #type: Directory
            
      containers:
        - name: "tinc-mesh-tunnel"
          image: "cssauth.azurecr.io/aksdevjpeastsandbox:latest"
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /etc/tinc/
            name: test-volume
          - mountPath: /dev/net/
            name: test-volume1
          - mountPath: /sysproc/sys/net/ipv4/conf/
            name: test-volume2
          #- mountPath: /proc/sys/net/ipv4/conf/tun0/
            #name: test-volume3
            #name: css-tinc-properties
          #Mounts:
            #/etc/tinc from mssqldb (rw)
                                     
          #volumeMounts:
           # - mountPath: /opt
           #   name: css-tinc-properties
          #lifecycle:
            #postStart:
              #exec:
                #command:
                 # - /bin/sh
                 # - -c
                 # - cp /opt/* /etc/tinc/floydonet/
