apiVersion: v1
kind: Service
metadata:
    name: "tinc-router-service"
    namespace : "product"
    labels:
        app: "tinc-router-service"
spec:
    type: LoadBalancer
    #type: ClusterIP
    ports:
    - port: 22
      targetPort: 22
      protocol: TCP
      name: ssh-tcp
    - port: 22
      targetPort: 22
      protocol: UDP
      name: ssh-udp
    - port: 655
      targetPort: 655
      protocol: TCP
      name: tinc-vpn-tcp
    - port: 655
      targetPort: 655
      protocol: UDP
      name: tinc-vpn-udp
    selector:
        app: "tinc-router"
